name: mvvm_template
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  retrofit: ^4.0.1
  analyzer: ^6.2.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  freezed: ^2.4.2
  get_it: ^7.6.0
  lottie: ^2.6.0
  country_code_picker: ^3.0.0
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.2
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.2
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
  assets:
    - assets/images/
    - assets/json/
    - assets/translations/

